# ================================================
# DO NOT EDIT THIS FILE
# ================================================
class TicTacToe:
    def __init__(self):
        self.board = [0] * 9   # 0 empty, 1 X, -1 O
        self.current_player = 1

    def clone(self):
        env = TicTacToe()
        env.board = self.board[:]
        env.current_player = self.current_player
        return env

    def moves(self):
        return [i for i, v in enumerate(self.board) if v == 0]

    def play(self, move):
        self.board[move] = self.current_player
        self.current_player *= -1

    def winner(self):
        wins = [(0,1,2),(3,4,5),(6,7,8),(0,3,6),
                (1,4,7),(2,5,8),(0,4,8),(2,4,6)]
        for a,b,c in wins:
            s = self.board[a] + self.board[b] + self.board[c]
            if s == 3: return 1
            if s == -3: return -1
        if 0 not in self.board: return 0
        return None
