# ================================================
# DO NOT EDIT THIS FILE
# ================================================
from .game import TicTacToe
from .tree import Node
from .mcts import mcts
def play_game(model1, model2, sims=50):
    env = TicTacToe()
    models = {1: model1, -1: model2}

    while env.winner() is None:
        root = Node(env.clone())
        move = mcts(root, models[env.current_player], n_simulations=sims)
        env.play(move)

    return env.winner()