# ================================================
# DO NOT EDIT THIS FILE
# ================================================
import math
class Node:
    def __init__(self, state, parent=None):
        self.state = state
        self.parent = parent
        self.children = {}
        self.visits = 0
        self.value = 0.0

    def is_leaf(self):
        return len(self.children) == 0

    def ucb_score(self, child, c=1.4):
        if child.visits == 0:
            return float("inf")
        return (child.value / child.visits +
                c * math.sqrt(math.log(self.visits) / child.visits))

    def best_child(self, c=1.4):
        return max(self.children.values(), key=lambda child: self.ucb_score(child, c))
